export const dummyReviews = [
    {
        id: 1,
        review: "My experience with Mark is a complete success, from outstanding customer service to a wide range of top-notch products. The store is always clean, and the purchasing experience is seamless. I also appreciate the informative newsletter. Thank you!",
        author: "Leona Paul",
        position: "CEO of Floatcom",
    },
    {
        id: 2,
        review: "Mark's dedication to customer service is unparalleled. The store's product range is impressive, and the clean and organized layout enhances the overall experience. The newsletter keeps me informed. Thank you!",
        author: "John Smith",
        position: "CTO of Tech Innovators",
    },
    {
        id: 3,
        review: "I am impressed with the level of service provided by Mark and his team. The store is well-maintained, and the purchasing process is straightforward. The newsletter adds value with its informative content. Thank you!",
        author: "Emily Johnson",
        position: "Marketing Director at Innovate Corp",
    },
    {
        id: 4,
        review: "Mark's commitment to excellence is evident in every aspect of the store. The product variety is exceptional, the store is clean, and the purchasing experience is smooth. The newsletter is a great source of information. Thank you!",
        author: "Alex Turner",
        position: "Founder of Tech Ventures",
    },
    {
        id: 5,
        review: "I've had a positive experience with Mark's store. The customer service is excellent, the product selection is diverse, and the clean store layout makes shopping enjoyable. The newsletter is a valuable addition. Thank you!",
        author: "Sophia Davis",
        position: "CEO of Innovate Solutions",
    },
];

export const ProductsData = [
    {
        Category: {
            id: 1,
            name: "Electronics",
            image: "electronics.jpg",
            SubCategory: [
                {
                    name: "Smartphones",
                    image: "smartphones.jpg",
                    products: [
                        {
                            batchNo: "B001",
                            uid: "UID001",
                            name: "Smartphone A",
                            price: 599,
                            description: "A high-end smartphone",
                            image: ["phoneA_front.jpg", "phoneA_back.jpg"],
                            video: ["phoneA_demo.mp4"],
                            category: "Electronics",
                            brand: "BrandX",
                            countInStock: 50,
                            avgRating: 4,
                            numReviews: 30,
                            isBlocked: false,
                        },
                        {
                            batchNo: "B002",
                            uid: "UID002",
                            name: "Smartphone A",
                            price: 599,
                            description: "A high-end smartphone",
                            image: ["phoneA_front.jpg", "phoneA_back.jpg"],
                            video: ["phoneA_demo.mp4"],
                            category: "Electronics",
                            brand: "BrandX",
                            countInStock: 50,
                            avgRating: 4,
                            numReviews: 30,
                            isBlocked: false,
                        },

                        {
                            batchNo: "B003",
                            uid: "UID003",
                            name: "Smartphone A",
                            price: 599,
                            description: "A high-end smartphone",
                            image: ["phoneA_front.jpg", "phoneA_back.jpg"],
                            video: ["phoneA_demo.mp4"],
                            category: "Electronics",
                            brand: "BrandX",
                            countInStock: 50,
                            avgRating: 4,
                            numReviews: 30,
                            isBlocked: false,
                        },
                        {
                            batchNo: "B004",
                            uid: "UID004",
                            name: "Smartphone A",
                            price: 599,
                            description: "A high-end smartphone",
                            image: ["phoneA_front.jpg", "phoneA_back.jpg"],
                            video: ["phoneA_demo.mp4"],
                            category: "Electronics",
                            brand: "BrandX",
                            countInStock: 50,
                            avgRating: 4,
                            numReviews: 30,
                            isBlocked: false,
                        },
                        {
                            batchNo: "B005",
                            uid: "UID005",
                            name: "Smartphone A",
                            price: 599,
                            description: "A high-end smartphone",
                            image: ["phoneA_front.jpg", "phoneA_back.jpg"],
                            video: ["phoneA_demo.mp4"],
                            category: "Electronics",
                            brand: "BrandX",
                            countInStock: 50,
                            avgRating: 4,
                            numReviews: 30,
                            isBlocked: false,
                        },
                    ],
                },
                {
                    name: "tablet",
                    image: "tablet.jpg",
                    products: [
                        {
                            batchNo: "B001",
                            uid: "UID001",
                            name: "Smartphone A",
                            price: 599,
                            description: "A high-end smartphone",
                            image: ["phoneA_front.jpg", "phoneA_back.jpg"],
                            video: ["phoneA_demo.mp4"],
                            category: "Electronics",
                            brand: "BrandX",
                            countInStock: 50,
                            avgRating: 4,
                            numReviews: 30,
                            isBlocked: false,
                        },
                        {
                            batchNo: "B002",
                            uid: "UID002",
                            name: "Smartphone A",
                            price: 599,
                            description: "A high-end smartphone",
                            image: ["phoneA_front.jpg", "phoneA_back.jpg"],
                            video: ["phoneA_demo.mp4"],
                            category: "Electronics",
                            brand: "BrandX",
                            countInStock: 50,
                            avgRating: 4,
                            numReviews: 30,
                            isBlocked: false,
                        },

                        {
                            batchNo: "B003",
                            uid: "UID003",
                            name: "Smartphone A",
                            price: 599,
                            description: "A high-end smartphone",
                            image: ["phoneA_front.jpg", "phoneA_back.jpg"],
                            video: ["phoneA_demo.mp4"],
                            category: "Electronics",
                            brand: "BrandX",
                            countInStock: 50,
                            avgRating: 4,
                            numReviews: 30,
                            isBlocked: false,
                        },
                        {
                            batchNo: "B004",
                            uid: "UID004",
                            name: "Smartphone A",
                            price: 599,
                            description: "A high-end smartphone",
                            image: ["phoneA_front.jpg", "phoneA_back.jpg"],
                            video: ["phoneA_demo.mp4"],
                            category: "Electronics",
                            brand: "BrandX",
                            countInStock: 50,
                            avgRating: 4,
                            numReviews: 30,
                            isBlocked: false,
                        },
                        {
                            batchNo: "B005",
                            uid: "UID005",
                            name: "Smartphone A",
                            price: 599,
                            description: "A high-end smartphone",
                            image: ["phoneA_front.jpg", "phoneA_back.jpg"],
                            video: ["phoneA_demo.mp4"],
                            category: "Electronics",
                            brand: "BrandX",
                            countInStock: 50,
                            avgRating: 4,
                            numReviews: 30,
                            isBlocked: false,
                        },
                    ],
                },
                {
                    name: "laptop",
                    image: "laptop.jpg",
                    products: [
                        {
                            batchNo: "B001",
                            uid: "UID001",
                            name: "Smartphone A",
                            price: 599,
                            description: "A high-end smartphone",
                            image: ["phoneA_front.jpg", "phoneA_back.jpg"],
                            video: ["phoneA_demo.mp4"],
                            category: "Electronics",
                            brand: "BrandX",
                            countInStock: 50,
                            avgRating: 4,
                            numReviews: 30,
                            isBlocked: false,
                        },
                        {
                            batchNo: "B002",
                            uid: "UID002",
                            name: "Smartphone A",
                            price: 599,
                            description: "A high-end smartphone",
                            image: ["phoneA_front.jpg", "phoneA_back.jpg"],
                            video: ["phoneA_demo.mp4"],
                            category: "Electronics",
                            brand: "BrandX",
                            countInStock: 50,
                            avgRating: 4,
                            numReviews: 30,
                            isBlocked: false,
                        },

                        {
                            batchNo: "B003",
                            uid: "UID003",
                            name: "Smartphone A",
                            price: 599,
                            description: "A high-end smartphone",
                            image: ["phoneA_front.jpg", "phoneA_back.jpg"],
                            video: ["phoneA_demo.mp4"],
                            category: "Electronics",
                            brand: "BrandX",
                            countInStock: 50,
                            avgRating: 4,
                            numReviews: 30,
                            isBlocked: false,
                        },
                        {
                            batchNo: "B004",
                            uid: "UID004",
                            name: "Smartphone A",
                            price: 599,
                            description: "A high-end smartphone",
                            image: ["phoneA_front.jpg", "phoneA_back.jpg"],
                            video: ["phoneA_demo.mp4"],
                            category: "Electronics",
                            brand: "BrandX",
                            countInStock: 50,
                            avgRating: 4,
                            numReviews: 30,
                            isBlocked: false,
                        },
                        {
                            batchNo: "B005",
                            uid: "UID005",
                            name: "Smartphone A",
                            price: 599,
                            description: "A high-end smartphone",
                            image: ["phoneA_front.jpg", "phoneA_back.jpg"],
                            video: ["phoneA_demo.mp4"],
                            category: "Electronics",
                            brand: "BrandX",
                            countInStock: 50,
                            avgRating: 4,
                            numReviews: 30,
                            isBlocked: false,
                        },
                    ],
                },
            ],
        },
    },
    {
        Category: {
            id: 2,
            name: "Clothing",
            image: "clothing.jpg",
            SubCategory: [
                {
                    name: "Men",
                    image: "men_clothing.jpg",
                    products: [
                        {
                            batchNo: "B101",
                            uid: "UID101",
                            name: "Men's Shirt",
                            price: 39,
                            description: "Casual shirt for men",
                            image: ["shirt_men_front.jpg", "shirt_men_back.jpg"],
                            video: ["shirt_men_demo.mp4"],
                            category: "Clothing",
                            brand: "FashionStyle",
                            countInStock: 100,
                            avgRating: 4.5,
                            numReviews: 25,
                            isBlocked: false,
                        },
                        {
                            batchNo: "B102",
                            uid: "UID102",
                            name: "Men's Shirt",
                            price: 39,
                            description: "Casual shirt for men",
                            image: ["shirt_men_front.jpg", "shirt_men_back.jpg"],
                            video: ["shirt_men_demo.mp4"],
                            category: "Clothing",
                            brand: "FashionStyle",
                            countInStock: 100,
                            avgRating: 4.5,
                            numReviews: 25,
                            isBlocked: false,
                        },
                        {
                            batchNo: "B103",
                            uid: "UID103",
                            name: "Men's Shirt",
                            price: 39,
                            description: "Casual shirt for men",
                            image: ["shirt_men_front.jpg", "shirt_men_back.jpg"],
                            video: ["shirt_men_demo.mp4"],
                            category: "Clothing",
                            brand: "FashionStyle",
                            countInStock: 100,
                            avgRating: 4.5,
                            numReviews: 25,
                            isBlocked: false,
                        },
                        // Add more products as needed
                    ],
                },
                {
                    name: "Women",
                    image: "men_clothing.jpg",
                    products: [
                        {
                            batchNo: "B101",
                            uid: "UID101",
                            name: "Men's Shirt",
                            price: 39,
                            description: "Casual shirt for men",
                            image: ["shirt_men_front.jpg", "shirt_men_back.jpg"],
                            video: ["shirt_men_demo.mp4"],
                            category: "Clothing",
                            brand: "FashionStyle",
                            countInStock: 100,
                            avgRating: 4.5,
                            numReviews: 25,
                            isBlocked: false,
                        },
                        {
                            batchNo: "B102",
                            uid: "UID102",
                            name: "Men's Shirt",
                            price: 39,
                            description: "Casual shirt for men",
                            image: ["shirt_men_front.jpg", "shirt_men_back.jpg"],
                            video: ["shirt_men_demo.mp4"],
                            category: "Clothing",
                            brand: "FashionStyle",
                            countInStock: 100,
                            avgRating: 4.5,
                            numReviews: 25,
                            isBlocked: false,
                        },
                        {
                            batchNo: "B103",
                            uid: "UID103",
                            name: "Men's Shirt",
                            price: 39,
                            description: "Casual shirt for men",
                            image: ["shirt_men_front.jpg", "shirt_men_back.jpg"],
                            video: ["shirt_men_demo.mp4"],
                            category: "Clothing",
                            brand: "FashionStyle",
                            countInStock: 100,
                            avgRating: 4.5,
                            numReviews: 25,
                            isBlocked: false,
                        },
                        // Add more products as needed
                    ],
                },
                {
                    name: "Kids",
                    image: "men_clothing.jpg",
                    products: [
                        {
                            batchNo: "B101",
                            uid: "UID101",
                            name: "Men's Shirt",
                            price: 39,
                            description: "Casual shirt for men",
                            image: ["shirt_men_front.jpg", "shirt_men_back.jpg"],
                            video: ["shirt_men_demo.mp4"],
                            category: "Clothing",
                            brand: "FashionStyle",
                            countInStock: 100,
                            avgRating: 4.5,
                            numReviews: 25,
                            isBlocked: false,
                        },
                        {
                            batchNo: "B102",
                            uid: "UID102",
                            name: "Men's Shirt",
                            price: 39,
                            description: "Casual shirt for men",
                            image: ["shirt_men_front.jpg", "shirt_men_back.jpg"],
                            video: ["shirt_men_demo.mp4"],
                            category: "Clothing",
                            brand: "FashionStyle",
                            countInStock: 100,
                            avgRating: 4.5,
                            numReviews: 25,
                            isBlocked: false,
                        },
                        {
                            batchNo: "B103",
                            uid: "UID103",
                            name: "Men's Shirt",
                            price: 39,
                            description: "Casual shirt for men",
                            image: ["shirt_men_front.jpg", "shirt_men_back.jpg"],
                            video: ["shirt_men_demo.mp4"],
                            category: "Clothing",
                            brand: "FashionStyle",
                            countInStock: 100,
                            avgRating: 4.5,
                            numReviews: 25,
                            isBlocked: false,
                        },
                        // Add more products as needed
                    ],
                },
            ],
        },
    },
    {
        Category: {
            id: 3,
            name: "Jewllery",
            image: "Jewllery.jpg",
            SubCategory: [
                {
                    name: "Men",
                    image: "men_clothing.jpg",
                    products: [
                        {
                            batchNo: "B101",
                            uid: "UID101",
                            name: "Men's Shirt",
                            price: 39,
                            description: "Casual shirt for men",
                            image: ["shirt_men_front.jpg", "shirt_men_back.jpg"],
                            video: ["shirt_men_demo.mp4"],
                            category: "Clothing",
                            brand: "FashionStyle",
                            countInStock: 100,
                            avgRating: 4.5,
                            numReviews: 25,
                            isBlocked: false,
                        },
                        {
                            batchNo: "B102",
                            uid: "UID102",
                            name: "Men's Shirt",
                            price: 39,
                            description: "Casual shirt for men",
                            image: ["shirt_men_front.jpg", "shirt_men_back.jpg"],
                            video: ["shirt_men_demo.mp4"],
                            category: "Clothing",
                            brand: "FashionStyle",
                            countInStock: 100,
                            avgRating: 4.5,
                            numReviews: 25,
                            isBlocked: false,
                        },
                        {
                            batchNo: "B103",
                            uid: "UID103",
                            name: "Men's Shirt",
                            price: 39,
                            description: "Casual shirt for men",
                            image: ["shirt_men_front.jpg", "shirt_men_back.jpg"],
                            video: ["shirt_men_demo.mp4"],
                            category: "Clothing",
                            brand: "FashionStyle",
                            countInStock: 100,
                            avgRating: 4.5,
                            numReviews: 25,
                            isBlocked: false,
                        },
                        // Add more products as needed
                    ],
                },
                {
                    name: "Women",
                    image: "men_clothing.jpg",
                    products: [
                        {
                            batchNo: "B101",
                            uid: "UID101",
                            name: "Men's Shirt",
                            price: 39,
                            description: "Casual shirt for men",
                            image: ["shirt_men_front.jpg", "shirt_men_back.jpg"],
                            video: ["shirt_men_demo.mp4"],
                            category: "Clothing",
                            brand: "FashionStyle",
                            countInStock: 100,
                            avgRating: 4.5,
                            numReviews: 25,
                            isBlocked: false,
                        },
                        {
                            batchNo: "B102",
                            uid: "UID102",
                            name: "Men's Shirt",
                            price: 39,
                            description: "Casual shirt for men",
                            image: ["shirt_men_front.jpg", "shirt_men_back.jpg"],
                            video: ["shirt_men_demo.mp4"],
                            category: "Clothing",
                            brand: "FashionStyle",
                            countInStock: 100,
                            avgRating: 4.5,
                            numReviews: 25,
                            isBlocked: false,
                        },
                        {
                            batchNo: "B103",
                            uid: "UID103",
                            name: "Men's Shirt",
                            price: 39,
                            description: "Casual shirt for men",
                            image: ["shirt_men_front.jpg", "shirt_men_back.jpg"],
                            video: ["shirt_men_demo.mp4"],
                            category: "Clothing",
                            brand: "FashionStyle",
                            countInStock: 100,
                            avgRating: 4.5,
                            numReviews: 25,
                            isBlocked: false,
                        },
                        // Add more products as needed
                    ],
                },
                {
                    name: "Kids",
                    image: "men_clothing.jpg",
                    products: [
                        {
                            batchNo: "B101",
                            uid: "UID101",
                            name: "Men's Shirt",
                            price: 39,
                            description: "Casual shirt for men",
                            image: ["shirt_men_front.jpg", "shirt_men_back.jpg"],
                            video: ["shirt_men_demo.mp4"],
                            category: "Clothing",
                            brand: "FashionStyle",
                            countInStock: 100,
                            avgRating: 4.5,
                            numReviews: 25,
                            isBlocked: false,
                        },
                        {
                            batchNo: "B102",
                            uid: "UID102",
                            name: "Men's Shirt",
                            price: 39,
                            description: "Casual shirt for men",
                            image: ["shirt_men_front.jpg", "shirt_men_back.jpg"],
                            video: ["shirt_men_demo.mp4"],
                            category: "Clothing",
                            brand: "FashionStyle",
                            countInStock: 100,
                            avgRating: 4.5,
                            numReviews: 25,
                            isBlocked: false,
                        },
                        {
                            batchNo: "B103",
                            uid: "UID103",
                            name: "Men's Shirt",
                            price: 39,
                            description: "Casual shirt for men",
                            image: ["shirt_men_front.jpg", "shirt_men_back.jpg"],
                            video: ["shirt_men_demo.mp4"],
                            category: "Clothing",
                            brand: "FashionStyle",
                            countInStock: 100,
                            avgRating: 4.5,
                            numReviews: 25,
                            isBlocked: false,
                        },
                        // Add more products as needed
                    ],
                },
            ],
        },
    },
    // Add more categories as needed
];
